import { useState } from 'react'
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import { Brand } from '@/constants/theme'
import { HOLDER_ACTIVITY, VERIFICATION_REQUESTS } from '@/data/holderMockData'

export default function ActivityScreen() {
  const [tab, setTab] = useState<'activity' | 'verifications'>('activity')
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Activity</Text><Text style={s.subtitle}>Track what's happening with your credentials.</Text><View style={s.tabs}>{[['activity', 'Activity'], ['verifications', 'My Verifications']].map(([id, label]) => <TouchableOpacity key={id} onPress={() => setTab(id as 'activity' | 'verifications')} style={[s.tab, tab === id && s.tabActive]}><Text style={[s.tabText, tab === id && s.tabTextActive]}>{label}</Text></TouchableOpacity>)}</View>{tab === 'activity' ? <View style={s.card}>{HOLDER_ACTIVITY.map(item => <View key={item.text + item.detail} style={s.row}><View style={[s.icon, { backgroundColor: item.bg }]}><Ionicons name={item.icon} size={17} color={item.color} /></View><View style={{ flex: 1 }}><Text style={s.name}>{item.text}</Text><Text style={s.muted}>{item.detail}</Text></View><Text style={s.date}>{item.date}</Text></View>)}</View> : <><View style={s.stats}>{[['Total', '12'], ['Successful', '11'], ['Failed', '1']].map(item => <View key={item[0]} style={s.stat}><Text style={s.muted}>{item[0]}</Text><Text style={s.value}>{item[1]}</Text></View>)}</View><View style={s.card}>{VERIFICATION_REQUESTS.map(item => <View key={item.id} style={s.verification}><View style={{ flex: 1 }}><Text style={s.name}>{item.certificate}</Text><Text style={s.muted}>{item.verifier}</Text></View><Text style={[s.result, { color: item.status === 'Failed' ? Brand.danger : Brand.success }]}>{item.status === 'Failed' ? 'Failed' : 'Success'}</Text></View>)}</View></>}</ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: Brand.bg2 }, content: { padding: 20, gap: 12, paddingBottom: 32 }, title: { fontSize: 24, fontWeight: '800', color: Brand.navy }, subtitle: { fontSize: 13, color: Brand.navy, opacity: 0.55 }, tabs: { flexDirection: 'row', alignSelf: 'flex-start', padding: 4, gap: 4, borderRadius: 13, backgroundColor: Brand.bg3 }, tab: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 9 }, tabActive: { backgroundColor: Brand.blue }, tabText: { fontSize: 12, fontWeight: '600', color: '#4A5578' }, tabTextActive: { color: 'white' }, card: { padding: 16, borderRadius: 17, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#F0F3FC' }, icon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 13, fontWeight: '600', color: Brand.navy }, muted: { fontSize: 11.5, color: Brand.navy, opacity: 0.5, marginTop: 2 }, date: { fontSize: 10.5, color: '#9AA3C2' }, stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, padding: 14, borderRadius: 14, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2 }, value: { fontSize: 24, fontWeight: '800', color: Brand.navy, marginTop: 4 }, verification: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#F0F3FC' }, result: { fontSize: 11, fontWeight: '700' } })