import { useMemo, useState } from 'react'
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import { useRouter } from 'expo-router'
import { Brand } from '@/constants/theme'
import { HOLDER_CERTIFICATES } from '@/data/holderMockData'

const filters = ['All', 'Degree', 'Course', 'Internship', 'Training', 'Other']

export default function CertificatesScreen() {
  const router = useRouter()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All')
  const filtered = useMemo(() => HOLDER_CERTIFICATES.filter(cert => (filter === 'All' || cert.type === filter) && `${cert.title} ${cert.issuer}`.toLowerCase().includes(query.toLowerCase())), [filter, query])
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <Text style={s.title}>My Certificates</Text><Text style={s.subtitle}>Your digital credential wallet - {HOLDER_CERTIFICATES.length} credentials</Text>
    <View style={s.search}><Ionicons name="search-outline" size={17} color="#8993B4" /><TextInput value={query} onChangeText={setQuery} placeholder="Search certificates..." placeholderTextColor="#9AA3C2" style={s.searchInput} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(item => <TouchableOpacity key={item} onPress={() => setFilter(item)} style={[s.filter, filter === item && s.filterActive]}><Text style={[s.filterText, filter === item && s.filterTextActive]}>{item}</Text></TouchableOpacity>)}</ScrollView>
    {filtered.length === 0 ? <View style={s.empty}><Text style={s.muted}>No certificates match your search.</Text></View> : filtered.map(cert => <View key={cert.id} style={s.card}><View style={s.cardTop}><View style={s.certIcon}><Text style={s.emoji}>{cert.icon}</Text></View><View style={[s.status, cert.status === 'Verified' ? s.verified : s.revoked]}><Ionicons name={cert.status === 'Verified' ? 'shield-checkmark-outline' : 'shield-outline'} size={13} color={cert.status === 'Verified' ? Brand.success : Brand.danger} /><Text style={{ color: cert.status === 'Verified' ? Brand.success : Brand.danger, fontSize: 11, fontWeight: '700' }}>{cert.status}</Text></View></View><Text style={s.cardTitle}>{cert.title}</Text><Text style={s.muted}>{cert.issuer}</Text><Text style={s.small}>Issued: {cert.issued}</Text><Text style={s.id}>{cert.id}</Text><View style={s.actions}><TouchableOpacity style={s.outline} onPress={() => router.push('/(holder)/verification')}><Ionicons name="eye-outline" size={15} color={Brand.navy} /><Text style={s.outlineText}>View</Text></TouchableOpacity><TouchableOpacity style={s.primary} onPress={() => router.push('/(holder)/share')}><Ionicons name="share-social-outline" size={15} color="white" /><Text style={s.primaryText}>Share</Text></TouchableOpacity></View></View>)}
  </ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: Brand.bg2 }, content: { padding: 20, gap: 12, paddingBottom: 32 }, title: { fontSize: 26, fontWeight: '800', color: Brand.navy }, subtitle: { fontSize: 13, color: Brand.navy, opacity: 0.5 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13, height: 44, borderRadius: 12, borderWidth: 1, borderColor: Brand.lightBlue2, backgroundColor: 'white', marginTop: 6 }, searchInput: { flex: 1, color: Brand.navy, fontSize: 13 }, filters: { gap: 8, paddingVertical: 4 }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: Brand.lightBlue2, backgroundColor: 'white' }, filterActive: { backgroundColor: Brand.blue, borderColor: Brand.blue }, filterText: { fontSize: 12, fontWeight: '600', color: '#4A5578' }, filterTextActive: { color: 'white' }, card: { padding: 16, borderRadius: 17, borderWidth: 1, borderColor: Brand.lightBlue2, backgroundColor: 'white', gap: 5 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 5 }, certIcon: { width: 46, height: 46, borderRadius: 12, backgroundColor: Brand.lightBlue, alignItems: 'center', justifyContent: 'center' }, emoji: { fontSize: 22 }, status: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 14 }, verified: { backgroundColor: '#E8F9EF' }, revoked: { backgroundColor: '#FDEDEE' }, cardTitle: { fontSize: 15, fontWeight: '700', color: Brand.navy, marginTop: 3 }, muted: { color: Brand.navy, opacity: 0.55, fontSize: 12.5 }, small: { color: Brand.navy, opacity: 0.4, fontSize: 11, marginTop: 5 }, id: { color: '#B3BAD4', fontSize: 10.5 }, actions: { flexDirection: 'row', gap: 8, borderTopWidth: 1, borderTopColor: '#F0F3FC', paddingTop: 12, marginTop: 8 }, outline: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5, paddingVertical: 9, borderRadius: 10, borderWidth: 1, borderColor: Brand.lightBlue2 }, outlineText: { color: Brand.navy, fontSize: 12, fontWeight: '600' }, primary: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5, paddingVertical: 9, borderRadius: 10, backgroundColor: Brand.blue }, primaryText: { color: 'white', fontSize: 12, fontWeight: '700' }, empty: { padding: 32, alignItems: 'center', backgroundColor: 'white', borderRadius: 16 } })