import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import { useRouter } from 'expo-router'
import { Brand } from '@/constants/theme'
import { HOLDER_ACTIVITY } from '@/data/holderMockData'

const stats = [
  { label: 'Total Certificates', value: '7', icon: 'ribbon-outline' as const, color: Brand.blue, bg: Brand.lightBlue },
  { label: 'Verified', value: '7', icon: 'shield-checkmark-outline' as const, color: Brand.success, bg: '#E8F9EF' },
  { label: 'Revoked', value: '0', icon: 'shield-outline' as const, color: Brand.danger, bg: '#FDEDEE' },
]

export default function HolderHome() {
  const router = useRouter() as any
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <Text style={s.eyebrow}>CERTIFICATE HOLDER</Text>
    <Text style={s.title}>Good evening, Atharv</Text>
    <Text style={s.subtitle}>Your credentials are safe and verified.</Text>
    <View style={s.stats}>{stats.map(stat => <View key={stat.label} style={s.statCard}><View style={[s.statIcon, { backgroundColor: stat.bg }]}><Ionicons name={stat.icon} size={21} color={stat.color} /></View><View><Text style={s.statLabel}>{stat.label}</Text><Text style={s.statValue}>{stat.value}</Text></View></View>)}</View>
    <View style={s.card}><Text style={s.sectionLabel}>RECENT CERTIFICATE</Text><View style={s.certRow}><View style={s.certIcon}><Text style={s.certEmoji}>🎓</Text></View><View style={s.certInfo}><Text style={s.certTitle}>B.E. Computer Engineering</Text><Text style={s.muted}>PCCOER</Text><Text style={s.smallMuted}>Issued: 15 June 2026</Text><Text style={s.verified}><Ionicons name="shield-checkmark" size={13} color={Brand.success} /> Verified</Text></View></View><View style={s.actions}><TouchableOpacity style={s.outlineBtn} onPress={() => router.push('/(holder)/certificates')}><Ionicons name="eye-outline" size={16} color={Brand.navy} /><Text style={s.outlineText}>View</Text></TouchableOpacity><TouchableOpacity style={s.primaryBtn} onPress={() => router.push('/(holder)/share')}><Ionicons name="share-social-outline" size={16} color="white" /><Text style={s.primaryText}>Share</Text></TouchableOpacity></View></View>
    <View style={s.card}><View style={s.headingRow}><Text style={s.sectionLabel}>RECENT ACTIVITY</Text><TouchableOpacity onPress={() => router.push('/(holder)/activity')}><Text style={s.link}>View All</Text></TouchableOpacity></View>{HOLDER_ACTIVITY.slice(0, 3).map(item => <View key={item.text + item.detail} style={s.activityRow}><View style={[s.activityIcon, { backgroundColor: item.bg }]}><Ionicons name={item.icon} size={16} color={item.color} /></View><View style={{ flex: 1 }}><Text style={s.activityText}>{item.text}</Text><Text style={s.smallMuted}>{item.detail} · {item.date}</Text></View></View>)}</View>
  </ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: Brand.bg2 }, content: { padding: 20, gap: 16, paddingBottom: 36 }, eyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 1.6, color: Brand.blue }, title: { fontSize: 26, fontWeight: '800', color: Brand.navy }, subtitle: { fontSize: 13, color: Brand.navy, opacity: 0.5, marginTop: -10 }, stats: { gap: 10 }, statCard: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 16, backgroundColor: 'white', borderRadius: 16, borderWidth: 1, borderColor: Brand.lightBlue2 }, statIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, statLabel: { fontSize: 12, color: Brand.navy, opacity: 0.55 }, statValue: { fontSize: 24, fontWeight: '800', color: Brand.navy }, card: { padding: 18, backgroundColor: 'white', borderRadius: 18, borderWidth: 1, borderColor: Brand.lightBlue2, gap: 14 }, sectionLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 1.2, color: '#8993B4' }, headingRow: { flexDirection: 'row', justifyContent: 'space-between' }, link: { fontSize: 12, fontWeight: '600', color: Brand.blue }, certRow: { flexDirection: 'row', gap: 12 }, certIcon: { width: 52, height: 52, borderRadius: 14, backgroundColor: Brand.lightBlue, alignItems: 'center', justifyContent: 'center' }, certEmoji: { fontSize: 24 }, certInfo: { flex: 1, gap: 2 }, certTitle: { fontSize: 15, fontWeight: '700', color: Brand.navy }, muted: { fontSize: 13, color: Brand.navy, opacity: 0.55 }, smallMuted: { fontSize: 11, color: Brand.navy, opacity: 0.4 }, verified: { alignSelf: 'flex-start', color: Brand.success, fontSize: 11, fontWeight: '700', marginTop: 3 }, actions: { flexDirection: 'row', gap: 10 }, outlineBtn: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, paddingVertical: 11, borderRadius: 11, borderWidth: 1, borderColor: Brand.bg5 }, outlineText: { color: Brand.navy, fontSize: 13, fontWeight: '600' }, primaryBtn: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, paddingVertical: 11, borderRadius: 11, backgroundColor: Brand.blue }, primaryText: { color: 'white', fontSize: 13, fontWeight: '700' }, activityRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, activityIcon: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, activityText: { fontSize: 13, color: Brand.navy, fontWeight: '600' } })