import { useState } from 'react'
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import { Brand } from '@/constants/theme'
import { ACTIVE_SHARES } from '@/data/holderMockData'

const fields = ['Degree', 'Institution', 'Issue date', 'Verification status', 'Personal address', 'Phone number']

export default function ShareScreen() {
  const [mode, setMode] = useState<'anyone' | 'specific'>('specific'); const [expiry, setExpiry] = useState('7'); const [generated, setGenerated] = useState(false); const [copied, setCopied] = useState(false); const [selected, setSelected] = useState(fields.slice(0, 4))
  const toggle = (field: string) => setSelected(value => value.includes(field) ? value.filter(item => item !== field) : [...value, field])
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Share Certificate</Text><Text style={s.subtitle}>Generate a secure, verifiable link instead of sending a plain PDF.</Text><View style={s.card}><Text style={s.label}>WHO ARE YOU SHARING WITH?</Text><View style={s.modeRow}>{[['anyone', 'Anyone with the link'], ['specific', 'Specific employer']].map(([id, label]) => <TouchableOpacity key={id} onPress={() => setMode(id as 'anyone' | 'specific')} style={[s.mode, mode === id && s.modeActive]}><Text style={s.modeTitle}>{label}</Text><Text style={s.muted}>{id === 'anyone' ? 'No recipient required' : 'Track purpose and access'}</Text></TouchableOpacity>)}</View>{mode === 'specific' && <View style={s.formRow}><View style={{ flex: 1 }}><Text style={s.inputLabel}>Employer</Text><TextInput defaultValue="ABC Technologies" style={s.input} /></View><View style={{ flex: 1 }}><Text style={s.inputLabel}>Purpose</Text><TextInput defaultValue="Job Application" style={s.input} /></View></View>}<Text style={s.inputLabel}>Link expiry</Text><View style={s.expiry}>{['1', '7', '14', '30'].map(day => <TouchableOpacity key={day} onPress={() => setExpiry(day)} style={[s.expiryBtn, expiry === day && s.expiryActive]}><Text style={[s.expiryText, expiry === day && s.expiryTextActive]}>{day} days</Text></TouchableOpacity>)}</View></View><View style={s.card}><Text style={s.label}>WHAT DO YOU WANT TO SHARE?</Text><Text style={s.muted}>Selective disclosure - choose exactly what the verifier can see.</Text>{fields.map(field => <TouchableOpacity key={field} onPress={() => toggle(field)} style={s.checkRow}><View style={[s.checkbox, selected.includes(field) && s.checked]}>{selected.includes(field) && <Ionicons name="checkmark" size={13} color="white" />}</View><Text style={s.field}>{field}</Text></TouchableOpacity>)}</View>{!generated ? <TouchableOpacity style={s.generate} onPress={() => setGenerated(true)}><Ionicons name="link-outline" size={17} color="white" /><Text style={s.generateText}>Generate Secure Link</Text></TouchableOpacity> : <View style={s.card}><Text style={s.label}>SECURE VERIFICATION LINK</Text><View style={s.linkBox}><Text numberOfLines={1} style={s.link}>certifyvault.com/share/8fK92xLq71QmP4</Text><TouchableOpacity onPress={() => { setCopied(true); setTimeout(() => setCopied(false), 1800) }}><Text style={s.copy}>{copied ? 'Copied' : 'Copy'}</Text></TouchableOpacity></View><Text style={s.muted}>Expires in {expiry} days · CV-VERIFY-8A72K9</Text></View>}<Text style={s.label}>ACTIVE SHARES</Text>{ACTIVE_SHARES.map(item => <View key={item.employer} style={s.shareRow}><View style={{ flex: 1 }}><Text style={s.name}>{item.employer}</Text><Text style={s.muted}>{item.purpose} · Created {item.created}</Text></View><Text style={[s.shareStatus, { color: item.status === 'Active' ? Brand.success : '#9AA3C2' }]}>{item.status === 'Active' ? `Expires ${item.expires}` : 'Expired'}</Text></View>)}</ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: Brand.bg2 }, content: { padding: 20, gap: 12, paddingBottom: 32 }, title: { fontSize: 24, fontWeight: '800', color: Brand.navy }, subtitle: { fontSize: 13, color: Brand.navy, opacity: 0.55, marginBottom: 5 }, card: { padding: 17, borderRadius: 17, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2, gap: 12 }, label: { fontSize: 10.5, fontWeight: '700', letterSpacing: 1.2, color: '#8993B4' }, modeRow: { gap: 9 }, mode: { padding: 13, borderRadius: 12, borderWidth: 1, borderColor: Brand.lightBlue2 }, modeActive: { borderColor: Brand.blue, backgroundColor: Brand.lightBlue }, modeTitle: { fontSize: 13, fontWeight: '700', color: Brand.navy }, muted: { fontSize: 11.5, color: Brand.navy, opacity: 0.5 }, formRow: { flexDirection: 'row', gap: 9 }, inputLabel: { fontSize: 11.5, fontWeight: '600', color: Brand.navy, opacity: 0.65, marginTop: 3 }, input: { marginTop: 5, paddingHorizontal: 10, height: 40, borderRadius: 10, borderWidth: 1, borderColor: Brand.lightBlue2, color: Brand.navy, fontSize: 12 }, expiry: { flexDirection: 'row', gap: 8 }, expiryBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 9, borderWidth: 1, borderColor: Brand.lightBlue2 }, expiryActive: { backgroundColor: Brand.blue, borderColor: Brand.blue }, expiryText: { fontSize: 11.5, color: '#4A5578', fontWeight: '600' }, expiryTextActive: { color: 'white' }, checkRow: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 7 }, checkbox: { width: 19, height: 19, borderRadius: 5, borderWidth: 1.5, borderColor: Brand.bg5, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: Brand.blue, borderColor: Brand.blue }, field: { fontSize: 13, color: Brand.navy }, generate: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7, paddingVertical: 14, borderRadius: 12, backgroundColor: Brand.blue }, generateText: { color: 'white', fontSize: 14, fontWeight: '700' }, linkBox: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 12, borderRadius: 10, backgroundColor: Brand.bg2 }, link: { flex: 1, color: Brand.navy, fontSize: 12, fontWeight: '600' }, copy: { color: Brand.blue, fontSize: 12, fontWeight: '700' }, shareRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 14, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2 }, name: { fontSize: 13, fontWeight: '700', color: Brand.navy }, shareStatus: { fontSize: 11, fontWeight: '700' } })