import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import { Brand } from '@/constants/theme'
import { VERIFICATION_REQUESTS } from '@/data/holderMockData'

export default function VerificationScreen() {
  const counts = { total: VERIFICATION_REQUESTS.length, verified: VERIFICATION_REQUESTS.filter(item => item.status === 'Verified').length, failed: VERIFICATION_REQUESTS.filter(item => item.status === 'Failed').length }
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Certificate Verification</Text><Text style={s.subtitle}>Track verification requests from employers and organizations.</Text><View style={s.stats}>{[['Total', counts.total, Brand.navy], ['Verified', counts.verified, Brand.success], ['Failed', counts.failed, Brand.danger]].map(([label, value, color]) => <View key={String(label)} style={s.stat}><Text style={s.label}>{label}</Text><Text style={[s.value, { color: color as string }]}>{value}</Text></View>)}</View><Text style={s.section}>VERIFICATION REQUESTS</Text>{VERIFICATION_REQUESTS.map(item => <View key={item.id} style={s.card}><View style={s.row}><View style={s.requestIcon}><Ionicons name={item.status === 'Verified' ? 'checkmark' : item.status === 'Pending' ? 'time-outline' : 'close'} size={18} color={item.status === 'Verified' ? Brand.success : item.status === 'Pending' ? Brand.warning : Brand.danger} /></View><View style={{ flex: 1 }}><Text style={s.name}>{item.verifier}</Text><Text style={s.muted}>{item.certificate}</Text><Text style={s.small}>{item.id} · {item.date}</Text></View></View><View style={[s.badge, { backgroundColor: item.status === 'Verified' ? '#E8F9EF' : item.status === 'Pending' ? '#FFF6E5' : '#FDEDEE' }]}><Text style={{ fontSize: 11, fontWeight: '700', color: item.status === 'Verified' ? Brand.success : item.status === 'Pending' ? Brand.warning : Brand.danger }}>{item.status}</Text></View><TouchableOpacity style={s.qrButton}><Ionicons name="qr-code-outline" size={15} color={Brand.blue} /><Text style={s.qrText}>View QR</Text></TouchableOpacity></View>)}</ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: Brand.bg2 }, content: { padding: 20, gap: 12, paddingBottom: 32 }, title: { fontSize: 24, fontWeight: '800', color: Brand.navy }, subtitle: { fontSize: 13, color: Brand.navy, opacity: 0.55 }, stats: { flexDirection: 'row', gap: 9, marginVertical: 8 }, stat: { flex: 1, padding: 14, borderRadius: 14, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2 }, label: { fontSize: 11, color: Brand.navy, opacity: 0.55 }, value: { fontSize: 25, fontWeight: '800', marginTop: 5 }, section: { fontSize: 11, fontWeight: '700', letterSpacing: 1.2, color: '#8993B4', marginTop: 5 }, card: { padding: 15, borderRadius: 16, backgroundColor: 'white', borderWidth: 1, borderColor: Brand.lightBlue2, gap: 10 }, row: { flexDirection: 'row', gap: 10 }, requestIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: Brand.lightBlue, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 13.5, fontWeight: '700', color: Brand.navy }, muted: { fontSize: 12, color: Brand.navy, opacity: 0.55, marginTop: 2 }, small: { fontSize: 10.5, color: Brand.navy, opacity: 0.4, marginTop: 3 }, badge: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 12 }, qrButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, borderRadius: 10, borderWidth: 1, borderColor: Brand.lightBlue2 }, qrText: { color: Brand.blue, fontSize: 12, fontWeight: '600' } })